steps:
  - name: node:16
    entrypoint: npm
    args: ['ci']

  - name: node:16
    entrypoint: npm
    args: ['run', 'build:ssr']

  - name: node:16
    entrypoint: npm
    args: ['run', 'build:assets']

  - name: node:16
    entrypoint: npm
    args: ['run', 'build:env']
    env:
      - 'API_TOKEN_SENDGRID=${_API_TOKEN_SENDGRID}'
      - 'API_TOKEN_SENDGRID_SOLVEO=${_API_TOKEN_SENDGRID_SOLVEO}'
      - 'API_TOKEN_GITHUB=${_API_TOKEN_GITHUB}'

  - name: gcr.io/cloud-builders/gcloud
    dir: dist/
    args:
      [
        'app',
        'deploy',
        '--promote',
        '--version=prod',
        '--stop-previous-version',
      ]
